### ISSUE TITLE
Little render error in docs: `bigmler delete`

### ISSUE THREAD

**Issue by osroca** [bigmlcom/bigmler#122]
the example on the option `--older-than` doesn't render correctly

`bigmler delete --older-than 2014-03-20 --newer-than 2014-03-19`

**Comment by mmerce** [comment]
Yes, the `--newer-than` option is mistyped. I'll add the typo correction to next release.

**Comment by osroca** [comment]
No, the `--newer-than` is correct, the problem is in the output of the example, that doesn't take the format of the other examples in the docs. My PR fixes it:

![image](https://cloud.githubusercontent.com/assets/743922/6374449/3de07f1c-bd11-11e4-95b2-e1f222798532.png)

BTW, there are other errors like this one, caused by a missing `\n` after the `::` directive.

**Comment by mmerce** [comment]
OK, that's why I see the single long dash in your message. I'll ask jao to add it to next.
