### ISSUE TITLE
uses 3gb+ memory running predictions

### ISSUE THREAD

**Issue by seamusabshere** [bigmlcom/bigmler#23]
![screen shot 2013-09-13 at 2 41 37 am](https://f.cloud.github.com/assets/15787/1136612/49b4627e-1c48-11e3-9ced-edb64f2af865.png)

here you can see an ensemble running

it seems to load half the models (1gb ram), run predictions, load the next half of models (2gb), run predictions and finally combine (3gb).

every time you load new models, can't you clear references to the old ones and let them be garbage collected?

**Comment by mmerce** [comment]
Closing the issue. If you experience this issue again, please reopen.
