### ISSUE TITLE
`--test-split` and `--json-filter` don't work together

### ISSUE THREAD

**Issue by seamusabshere** [bigmlcom/bigmler#30]
I've got a master dataset with lots of labels and features.

I want to manually generate a split for every label with `--test-split` so that I can create multiple ensembles and evaluations against it (different feature sets).

I want to use `--json-filter` to make sure that a split only contains labeled records - in other words, `["not",["missing", "labelX"]]`. That way I can ensure that train and test really are 70%/30%.

Currently, `--test-split` and `--json-filter` don't work together - the filter is ignored.

**Comment by mmerce** [comment]
Closing this issue. It was solved some time ago. If you experience the problem again, please reopen.
